2024-10-15 16:27:43,817 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Новая папка\pythonProject\test_12_4.py", line 23, in test_run
    runner = Runner(228, 10)
  File "D:\Новая папка\pythonProject\rt_with_exceptions.py", line 9, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-15 16:27:43,831 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Новая папка\pythonProject\test_12_4.py", line 13, in test_walk
    runner = Runner('Ivan', -5)
  File "D:\Новая папка\pythonProject\rt_with_exceptions.py", line 14, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
